#!/bin/bash

emmake make CPPFLAGS="-s TOTAL_MEMORY=256MB -s ALLOW_MEMORY_GROWTH=1 -s USE_ZLIB=1 -s USE_SDL=1 -s WASM=1" LDFLAGS="-s TOTAL_MEMORY=256MB -s ALLOW_MEMORY_GROWTH=1 -s WASM=1 -s USE_ZLIB=1 -s USE_SDL=1 --emrun --embed-file roms/rom.nds"  EXEEXT=.html
